### ISSUE TITLE
Please, add a license

### ISSUE THREAD

**Issue by oesteban** [SIMEXP/fmriprep-lts#4]
In NiPreps, we suggest Apache-2.0 ([see why here](https://www.nipreps.org/community/licensing/)), but this project may have any license if you have guidelines stating otherwise.

**Comment by lunebellec** [comment]
Apache-2.0 sounds good to me.

**Comment by ltetrel** [comment]
Thanks for the reminder.
Is this ok now @oesteban ?
https://github.com/SIMEXP/fmriprep-reproducibility/blob/master/LICENSE.txt

**Comment by oesteban** [comment]
Of course!
